# Generated by Django 4.2.19 on 2025-04-06 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0118_alter_skill_id'),
        ('hrcentre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterAuditLoginData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('characteraudit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_data', to='corptools.characteraudit')),
            ],
        ),
    ]
