# Generated by Django 4.2.21 on 2025-07-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrcentre', '0005_userscheck_alliancesetup_checks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelGrouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiple_selection', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('can_self_assign', models.BooleanField(default=False)),
                ('options', models.ManyToManyField(related_name='+', to='hrcentre.label')),
                ('show_to_alliances', models.ManyToManyField(blank=True, related_name='label_groupings', to='hrcentre.alliancesetup')),
                ('show_to_corporations', models.ManyToManyField(blank=True, related_name='label_groupings', to='hrcentre.corporationsetup')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
